/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandardIndexRouteImport } from './routes/standard/index'
import { Route as VerifyLitleIdRouteImport } from './routes/verify.$litleId'
import { Route as StandardTrustFabricRouteImport } from './routes/standard/trust-fabric'
import { Route as StandardRfcsRouteImport } from './routes/standard/rfcs'
import { Route as StandardObservabilityRouteImport } from './routes/standard/observability'
import { Route as StandardArchiveRouteImport } from './routes/standard/archive'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as StandardRfcsIndexRouteImport } from './routes/standard/rfcs.index'
import { Route as StandardRfcsSlugRouteImport } from './routes/standard/rfcs.$slug'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as StandardOpenScienceRouteImport } from './routes/standard/open-science'
import { Route as CertificateLitleIdRouteImport } from './routes/certificate.$litleId'
import { Route as StandardCertificationRouteImport } from './routes/standard/certification'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AdminQuarantineRouteImport } from './routes/admin/quarantine'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardOpenScienceRoute = StandardOpenScienceRouteImport.update({
  id: '/standard/open-science',
  path: '/standard/open-science',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateLitleIdRoute = CertificateLitleIdRouteImport.update({
  id: '/certificate/$litleId',
  path: '/certificate/$litleId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardCertificationRoute = StandardCertificationRouteImport.update({
  id: '/standard/certification',
  path: '/standard/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardIndexRoute = StandardIndexRouteImport.update({
  id: '/standard/',
  path: '/standard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyLitleIdRoute = VerifyLitleIdRouteImport.update({
  id: '/verify/$litleId',
  path: '/verify/$litleId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardTrustFabricRoute = StandardTrustFabricRouteImport.update({
  id: '/standard/trust-fabric',
  path: '/standard/trust-fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardRfcsRoute = StandardRfcsRouteImport.update({
  id: '/standard/rfcs',
  path: '/standard/rfcs',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardObservabilityRoute = StandardObservabilityRouteImport.update({
  id: '/standard/observability',
  path: '/standard/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardArchiveRoute = StandardArchiveRouteImport.update({
  id: '/standard/archive',
  path: '/standard/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute = AuthenticatedSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminQuarantineRoute = AdminQuarantineRouteImport.update({
  id: '/admin/quarantine',
  path: '/admin/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardRfcsIndexRoute = StandardRfcsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandardRfcsRoute,
} as any)
const StandardRfcsSlugRoute = StandardRfcsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StandardRfcsRoute,
} as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/governance': typeof GovernanceRoute
  '/submit': typeof SubmitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/standard/archive': typeof StandardArchiveRoute
  '/standard/observability': typeof StandardObservabilityRoute
  '/standard/open-science': typeof StandardOpenScienceRoute
  '/standard/certification': typeof StandardCertificationRoute
  '/certificate/$litleId': typeof CertificateLitleIdRoute
  '/standard/rfcs': typeof StandardRfcsRouteWithChildren
  '/standard/trust-fabric': typeof StandardTrustFabricRoute
  '/verify/$litleId': typeof VerifyLitleIdRoute
  '/standard/': typeof StandardIndexRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/standard/rfcs/$slug': typeof StandardRfcsSlugRoute
  '/standard/rfcs/': typeof StandardRfcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/governance': typeof GovernanceRoute
  '/submit': typeof SubmitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/standard/archive': typeof StandardArchiveRoute
  '/standard/observability': typeof StandardObservabilityRoute
  '/standard/open-science': typeof StandardOpenScienceRoute
  '/standard/certification': typeof StandardCertificationRoute
  '/certificate/$litleId': typeof CertificateLitleIdRoute
  '/standard/trust-fabric': typeof StandardTrustFabricRoute
  '/verify/$litleId': typeof VerifyLitleIdRoute
  '/standard': typeof StandardIndexRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/standard/rfcs/$slug': typeof StandardRfcsSlugRoute
  '/standard/rfcs': typeof StandardRfcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/governance': typeof GovernanceRoute
  '/submit': typeof SubmitRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/standard/archive': typeof StandardArchiveRoute
  '/standard/observability': typeof StandardObservabilityRoute
  '/standard/open-science': typeof StandardOpenScienceRoute
  '/standard/rfcs': typeof StandardRfcsRouteWithChildren
  '/standard/trust-fabric': typeof StandardTrustFabricRoute
  '/verify/$litleId': typeof VerifyLitleIdRoute
  '/standard/': typeof StandardIndexRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/standard/rfcs/$slug': typeof StandardRfcsSlugRoute
  '/standard/rfcs/': typeof StandardRfcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/discovery'
    | '/library'
    | '/governance'
    | '/submit'
    | '/dashboard'
    | '/standard/archive'
    | '/standard/observability'
    | '/standard/open-science'
    | '/standard/certification'
    | '/certificate/$litleId'
    | '/standard/rfcs'
    | '/standard/trust-fabric'
    | '/verify/$litleId'
    | '/standard/'
    | '/books/$bookId'
    | '/standard/rfcs/$slug'
    | '/standard/rfcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/discovery'
    | '/library'
    | '/governance'
    | '/submit'
    | '/dashboard'
    | '/standard/archive'
    | '/standard/observability'
    | '/standard/open-science'
    | '/standard/certification'
    | '/certificate/$litleId'
    | '/standard/trust-fabric'
    | '/verify/$litleId'
    | '/standard'
    | '/books/$bookId'
    | '/standard/rfcs/$slug'
    | '/standard/rfcs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/discovery'
    | '/library'
    | '/governance'
    | '/submit'
    | '/_authenticated/dashboard'
    | '/standard/archive'
    | '/standard/observability'
    | '/standard/open-science'
    | '/standard/certification'
    | '/certificate/$litleId'
    | '/standard/rfcs'
    | '/standard/trust-fabric'
    | '/verify/$litleId'
    | '/standard/'
    | '/_authenticated/books/$bookId'
    | '/standard/rfcs/$slug'
    | '/standard/rfcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DiscoveryRoute: typeof DiscoveryRoute
  LibraryRoute: typeof LibraryRoute
  GovernanceRoute: typeof GovernanceRoute
  SubmitRoute: typeof SubmitRoute
  AdminQuarantineRoute: typeof AdminQuarantineRoute
  StandardArchiveRoute: typeof StandardArchiveRoute
  StandardObservabilityRoute: typeof StandardObservabilityRoute
  StandardOpenScienceRoute: typeof StandardOpenScienceRoute
  StandardCertificationRoute: typeof StandardCertificationRoute
  CertificateLitleIdRoute: typeof CertificateLitleIdRoute
  StandardRfcsRoute: typeof StandardRfcsRouteWithChildren
  StandardTrustFabricRoute: typeof StandardTrustFabricRoute
  VerifyLitleIdRoute: typeof VerifyLitleIdRoute
  StandardIndexRoute: typeof StandardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/': {
      id: '/standard/'
      path: '/standard'
      fullPath: '/standard/'
      preLoaderRoute: typeof StandardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$litleId': {
      id: '/verify/$litleId'
      path: '/verify/$litleId'
      fullPath: '/verify/$litleId'
      preLoaderRoute: typeof VerifyLitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/trust-fabric': {
      id: '/standard/trust-fabric'
      path: '/standard/trust-fabric'
      fullPath: '/standard/trust-fabric'
      preLoaderRoute: typeof StandardTrustFabricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/rfcs': {
      id: '/standard/rfcs'
      path: '/standard/rfcs'
      fullPath: '/standard/rfcs'
      preLoaderRoute: typeof StandardRfcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/observability': {
      id: '/standard/observability'
      path: '/standard/observability'
      fullPath: '/standard/observability'
      preLoaderRoute: typeof StandardObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/open-science': {
      id: '/standard/open-science'
      path: '/standard/open-science'
      fullPath: '/standard/open-science'
      preLoaderRoute: typeof StandardOpenScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/certification': {
      id: '/standard/certification'
      path: '/standard/certification'
      fullPath: '/standard/certification'
      preLoaderRoute: typeof StandardCertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$litleId': {
      id: '/certificate/$litleId'
      path: '/certificate/$litleId'
      fullPath: '/certificate/$litleId'
      preLoaderRoute: typeof CertificateLitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard/archive': {
      id: '/standard/archive'
      path: '/standard/archive'
      fullPath: '/standard/archive'
      preLoaderRoute: typeof StandardArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/standard/rfcs/': {
      id: '/standard/rfcs/'
      path: '/'
      fullPath: '/standard/rfcs/'
      preLoaderRoute: typeof StandardRfcsIndexRouteImport
      parentRoute: typeof StandardRfcsRoute
    }
    '/standard/rfcs/$slug': {
      id: '/standard/rfcs/$slug'
      path: '/$slug'
      fullPath: '/standard/rfcs/$slug'
      preLoaderRoute: typeof StandardRfcsSlugRouteImport
      parentRoute: typeof StandardRfcsRoute
    }
    '/admin/quarantine': {
      id: '/admin/quarantine'
      path: '/admin/quarantine'
      fullPath: '/admin/quarantine'
      preLoaderRoute: typeof AdminQuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StandardRfcsRouteChildren {
  StandardRfcsSlugRoute: typeof StandardRfcsSlugRoute
  StandardRfcsIndexRoute: typeof StandardRfcsIndexRoute
}

const StandardRfcsRouteChildren: StandardRfcsRouteChildren = {
  StandardRfcsSlugRoute: StandardRfcsSlugRoute,
  StandardRfcsIndexRoute: StandardRfcsIndexRoute,
}

const StandardRfcsRouteWithChildren = StandardRfcsRoute._addFileChildren(
  StandardRfcsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DiscoveryRoute: DiscoveryRoute,
  LibraryRoute: LibraryRoute,
  GovernanceRoute: GovernanceRoute,
  SubmitRoute: SubmitRoute,
  AdminQuarantineRoute: AdminQuarantineRoute,
  StandardArchiveRoute: StandardArchiveRoute,
  StandardObservabilityRoute: StandardObservabilityRoute,
  StandardOpenScienceRoute: StandardOpenScienceRoute,
  StandardCertificationRoute: StandardCertificationRoute,
  CertificateLitleIdRoute: CertificateLitleIdRoute,
  StandardRfcsRoute: StandardRfcsRouteWithChildren,
  StandardTrustFabricRoute: StandardTrustFabricRoute,
  VerifyLitleIdRoute: VerifyLitleIdRoute,
  StandardIndexRoute: StandardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
